// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVotoElectronico.Api.Data;

#nullable disable

namespace SistemaVotoElectronico.Api.Migrations
{
    [DbContext(typeof(SistemaVotoElectronicoApiContext))]
    [Migration("20260216064102_AddSplitVotingEntities")]
    partial class AddSplitVotingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Asambleista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text");

                    b.Property<int>("ListaElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListaElectoralId");

                    b.ToTable("Asambleistas");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoEleccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.JefeDeMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("JefesDeMesa");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Logotipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.ToTable("ListaElectorales");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<int?>("JefeDeMesaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("JefeDeMesaId")
                        .IsUnique();

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.PadronElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CodigoCanjeado")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoEnlace")
                        .HasColumnType("text");

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaGeneracionCodigo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaVoto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MesaId")
                        .HasColumnType("integer");

                    b.Property<int?>("VotanteId")
                        .HasColumnType("integer");

                    b.Property<bool>("VotoNominalRealizado")
                        .HasColumnType("boolean");

                    b.Property<bool>("VotoPlanchaRealizado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEnlace");

                    b.HasIndex("EleccionId");

                    b.HasIndex("MesaId");

                    b.HasIndex("VotanteId");

                    b.ToTable("PadronElectorales");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Presidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text");

                    b.Property<int>("ListaElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListaElectoralId")
                        .IsUnique();

                    b.ToTable("Presidentes");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.SolicitudRecuperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SolicitudesRecuperacion");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Vicepresidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text");

                    b.Property<int>("ListaElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListaElectoralId")
                        .IsUnique();

                    b.ToTable("Vicepresidentes");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Voto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ListaAsambleistaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ListaPresidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("ListaAsambleistaId");

                    b.HasIndex("ListaPresidenteId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Asambleista", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", "ListaElectoral")
                        .WithMany("Asambleistas")
                        .HasForeignKey("ListaElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaElectoral");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.Eleccion", "Eleccion")
                        .WithMany("Listas")
                        .HasForeignKey("EleccionId");

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Mesa", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.Eleccion", "Eleccion")
                        .WithMany("Mesas")
                        .HasForeignKey("EleccionId");

                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.JefeDeMesa", "JefeDeMesa")
                        .WithOne("MesaAsignada")
                        .HasForeignKey("SistemaVotoElectronico.Modelos.Entidades.Mesa", "JefeDeMesaId");

                    b.Navigation("Eleccion");

                    b.Navigation("JefeDeMesa");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.PadronElectoral", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId");

                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.Votante", "Votante")
                        .WithMany("HistorialVotos")
                        .HasForeignKey("VotanteId");

                    b.Navigation("Eleccion");

                    b.Navigation("Mesa");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Presidente", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", "ListaElectoral")
                        .WithOne("Presidente")
                        .HasForeignKey("SistemaVotoElectronico.Modelos.Entidades.Presidente", "ListaElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaElectoral");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Vicepresidente", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", "ListaElectoral")
                        .WithOne("Vicepresidente")
                        .HasForeignKey("SistemaVotoElectronico.Modelos.Entidades.Vicepresidente", "ListaElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaElectoral");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Voto", b =>
                {
                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", "ListaAsambleista")
                        .WithMany()
                        .HasForeignKey("ListaAsambleistaId");

                    b.HasOne("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", "ListaPresidente")
                        .WithMany()
                        .HasForeignKey("ListaPresidenteId");

                    b.Navigation("Eleccion");

                    b.Navigation("ListaAsambleista");

                    b.Navigation("ListaPresidente");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Eleccion", b =>
                {
                    b.Navigation("Listas");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.JefeDeMesa", b =>
                {
                    b.Navigation("MesaAsignada");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.ListaElectoral", b =>
                {
                    b.Navigation("Asambleistas");

                    b.Navigation("Presidente");

                    b.Navigation("Vicepresidente");
                });

            modelBuilder.Entity("SistemaVotoElectronico.Modelos.Entidades.Votante", b =>
                {
                    b.Navigation("HistorialVotos");
                });
#pragma warning restore 612, 618
        }
    }
}
